name: Render and Deploy Quarto
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'
          
      - name: Install R Packages
        run: |
          R -e "install.packages('knitr', repos='https://cran.rstudio.com/')"
          R -e "install.packages('rmarkdown', repos='https://cran.rstudio.com/')"
          
      - name: Render Quarto
        run: quarto render myCV.qmd --to html
        
      - name: Rename to index.html
        run: mv myCV.html index.html
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages